/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.serdar.bankbalance.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** The key value type. */
@org.apache.avro.specific.AvroGenerated
public class Balance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1266423492706618164L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Balance\",\"namespace\":\"com.serdar.bankbalance.avro\",\"doc\":\"The key value type.\",\"fields\":[{\"name\":\"count\",\"type\":\"int\",\"doc\":\"The key string, must not be null.\"},{\"name\":\"balance\",\"type\":\"int\",\"doc\":\"The amount string, must not be null.\"},{\"name\":\"time\",\"type\":\"string\",\"doc\":\"The time string, must not be null.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Balance> ENCODER =
      new BinaryMessageEncoder<Balance>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Balance> DECODER =
      new BinaryMessageDecoder<Balance>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Balance> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Balance> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Balance>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Balance to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Balance from a ByteBuffer. */
  public static Balance fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The key string, must not be null. */
  @Deprecated public int count;
  /** The amount string, must not be null. */
  @Deprecated public int balance;
  /** The time string, must not be null. */
  @Deprecated public CharSequence time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Balance() {}

  /**
   * All-args constructor.
   * @param count The key string, must not be null.
   * @param balance The amount string, must not be null.
   * @param time The time string, must not be null.
   */
  public Balance(Integer count, Integer balance, CharSequence time) {
    this.count = count;
    this.balance = balance;
    this.time = time;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return count;
    case 1: return balance;
    case 2: return time;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: count = (Integer)value$; break;
    case 1: balance = (Integer)value$; break;
    case 2: time = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'count' field.
   * @return The key string, must not be null.
   */
  public Integer getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * The key string, must not be null.
   * @param value the value to set.
   */
  public void setCount(Integer value) {
    this.count = value;
  }

  /**
   * Gets the value of the 'balance' field.
   * @return The amount string, must not be null.
   */
  public Integer getBalance() {
    return balance;
  }

  /**
   * Sets the value of the 'balance' field.
   * The amount string, must not be null.
   * @param value the value to set.
   */
  public void setBalance(Integer value) {
    this.balance = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return The time string, must not be null.
   */
  public CharSequence getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * The time string, must not be null.
   * @param value the value to set.
   */
  public void setTime(CharSequence value) {
    this.time = value;
  }

  /**
   * Creates a new Balance RecordBuilder.
   * @return A new Balance RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Balance RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Balance RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Balance RecordBuilder by copying an existing Balance instance.
   * @param other The existing instance to copy.
   * @return A new Balance RecordBuilder
   */
  public static Builder newBuilder(Balance other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Balance instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Balance>
    implements org.apache.avro.data.RecordBuilder<Balance> {

    /** The key string, must not be null. */
    private int count;
    /** The amount string, must not be null. */
    private int balance;
    /** The time string, must not be null. */
    private CharSequence time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.balance)) {
        this.balance = data().deepCopy(fields()[1].schema(), other.balance);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.time)) {
        this.time = data().deepCopy(fields()[2].schema(), other.time);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Balance instance
     * @param other The existing instance to copy.
     */
    private Builder(Balance other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.count)) {
        this.count = data().deepCopy(fields()[0].schema(), other.count);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.balance)) {
        this.balance = data().deepCopy(fields()[1].schema(), other.balance);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.time)) {
        this.time = data().deepCopy(fields()[2].schema(), other.time);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'count' field.
      * The key string, must not be null.
      * @return The value.
      */
    public Integer getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * The key string, must not be null.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public Builder setCount(int value) {
      validate(fields()[0], value);
      this.count = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * The key string, must not be null.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'count' field.
      * The key string, must not be null.
      * @return This builder.
      */
    public Builder clearCount() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'balance' field.
      * The amount string, must not be null.
      * @return The value.
      */
    public Integer getBalance() {
      return balance;
    }

    /**
      * Sets the value of the 'balance' field.
      * The amount string, must not be null.
      * @param value The value of 'balance'.
      * @return This builder.
      */
    public Builder setBalance(int value) {
      validate(fields()[1], value);
      this.balance = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'balance' field has been set.
      * The amount string, must not be null.
      * @return True if the 'balance' field has been set, false otherwise.
      */
    public boolean hasBalance() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'balance' field.
      * The amount string, must not be null.
      * @return This builder.
      */
    public Builder clearBalance() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * The time string, must not be null.
      * @return The value.
      */
    public CharSequence getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * The time string, must not be null.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public Builder setTime(CharSequence value) {
      validate(fields()[2], value);
      this.time = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * The time string, must not be null.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'time' field.
      * The time string, must not be null.
      * @return This builder.
      */
    public Builder clearTime() {
      time = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Balance build() {
      try {
        Balance record = new Balance();
        record.count = fieldSetFlags()[0] ? this.count : (Integer) defaultValue(fields()[0]);
        record.balance = fieldSetFlags()[1] ? this.balance : (Integer) defaultValue(fields()[1]);
        record.time = fieldSetFlags()[2] ? this.time : (CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Balance>
    WRITER$ = (org.apache.avro.io.DatumWriter<Balance>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Balance>
    READER$ = (org.apache.avro.io.DatumReader<Balance>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
